# Generated by Django 2.0.3 on 2018-12-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topping',
            name='toppingPrice',
        ),
        migrations.AddField(
            model_name='addition',
            name='additionPrice',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=6),
            preserve_default=False,
        ),
    ]
