# Generated by Django 2.0.3 on 2018-12-15 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20181215_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizzaoption',
            name='category',
        ),
        migrations.RemoveField(
            model_name='pizzaoption',
            name='item',
        ),
        migrations.DeleteModel(
            name='PizzaOption',
        ),
    ]
